const express = require('express')
const mongoose = require('mongoose')
const passport = require('passport')
const bodyParser = require('body-parser')
const authRoutes = require ('./routes/auth')
const analyticsRoutes = require ('./routes/analytics')
const categoryRoutes = require ('./routes/category')
const orderRoutes = require ('./routes/order')
const positionRoutes = require ('./routes/position')
const keys = require ('./config/keys')
const app = express()

mongoose.connect('keys.mongoURI') 
.then (() => console.log('mongodb connected.'))
.catch(error => console.log(error))
/*  database url */

app.use(passport.initialize())
require('./middleware/passport')(passport)
app.use(require('morgan')('dev'))
app.use(require('cors')('dev'))
app.use('/api/auth', authRoutes)
app.use('/api/analytics', analyticsRoutes)
app.use('/api/category', categoryRoutes)
app.use('/api/order', orderRoutes)
app.use('/api/position', positionRoutes)
app.use(bodyParser.urlencoded({extended: true}))
app.use(bodyParser.json())
app.use(require('cors'()))
module.exports = app